Models/AddFuelDataModel.cs
namespace Fuel_Tracking_application.Models
{
    public class AddFuelDataModel
    {
        public string? reportingEmployee { get; set; }

        public DateTime Date { get; set; }

        public int odometerTotal { get; set; }

        public int filledVolume { get; set; }

        public int fuelPrice { get; set; }

        public string? filled { get; set; }
    }
}

Models/Domain/Fuel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Fuel_Tracking_application.Models.Domain
{
    public class Fuel
    {
        [Key]
        public Guid dataId { get; set; }

        public string? reportingEmployee { get; set; }

        public DateTime Date { get; set; }

        public int odometerTotal { get; set; }

        public int filledVolume { get; set; }

        public int fuelPrice { get; set; }

        public string? filled { get; set; }

       

    }
}

Models/ErrorViewModel.cs
namespace Fuel_Tracking_application.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UpdateFuelDataModel.cs
namespace Fuel_Tracking_application.Models
{
    public class UpdateFuelDataModel
    {
        public Guid dataId { get; set; }

        public string? reportingEmployee { get; set; }

        public DateTime Date { get; set; }

        public int odometerTotal { get; set; }

        public int filledVolume { get; set; }

        public int fuelPrice { get; set; }

        public string? filled { get; set; }
    }
}

Controllers/FuelDataController.cs
using Microsoft.AspNetCore.Mvc;
using Fuel_Tracking_application.Models.Domain;
using Fuel_Tracking_application.Models;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Fuel_Tracking_application.Data;
using Microsoft.EntityFrameworkCore;

namespace Fuel_Tracking_application.Controllers
{
    public class FuelDataController : Controller
    {
        private readonly FuelDbContext fuelDbContext;

        public FuelDataController(FuelDbContext fuelDbContext)
        {
            this.fuelDbContext = fuelDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var fuel = await fuelDbContext.FuelData.ToListAsync();
            return View(fuel);
        }

        [HttpGet] 
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddFuelDataModel addFuelDataRequest)
        {
            var fuel = new Fuel()
            {
                dataId = Guid.NewGuid(),
                reportingEmployee = addFuelDataRequest.reportingEmployee,
                Date = addFuelDataRequest.Date,
                odometerTotal = addFuelDataRequest.odometerTotal,  
                filled = addFuelDataRequest.filled,
                filledVolume = addFuelDataRequest.filledVolume,
                fuelPrice = addFuelDataRequest.fuelPrice

            };

            await fuelDbContext.FuelData.AddAsync(fuel);
            await fuelDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id) 
        {
           var fueldata = await fuelDbContext.FuelData.FirstOrDefaultAsync(x => x.dataId == id);

             
            if (fueldata != null)
            {
                var viewModel = new UpdateFuelDataModel()
                {
                    dataId = fueldata.dataId,
                    reportingEmployee = fueldata.reportingEmployee,
                    Date = fueldata.Date,
                    odometerTotal = fueldata.odometerTotal,
                    filled = fueldata.filled,
                    filledVolume = fueldata.filledVolume,
                    fuelPrice = fueldata.fuelPrice
                };

                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> View(UpdateFuelDataModel model)
        {
            var fuel = await fuelDbContext.FuelData.FindAsync(model.dataId);

            if (fuel != null)
            {
                fuel.reportingEmployee = model.reportingEmployee;
                fuel.Date = model.Date;
                fuel.odometerTotal = model.odometerTotal;
                fuel.filled = model.filled;
                fuel.filledVolume = model.filledVolume;

                await fuelDbContext.SaveChangesAsync();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateFuelDataModel model)
        {
            var fuel = fuelDbContext.FuelData.Find(model.dataId);

            if (fuel != null) 
            {
                fuelDbContext.FuelData.Remove(fuel);
                await fuelDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Fuel_Tracking_application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Fuel_Tracking_application.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public void ExportToExcel()
        {
            
        }
    }
}

Views/FuelData/Add.cshtml
@model Fuel_Tracking_application.Models.AddFuelDataModel
@{
}

<h1>Add Fuel Data</h1>
<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Reporting Employee Name</label>
        <input type="text" class="form-control" asp-for="reportingEmployee">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date of Log</label>
        <input type="date" class="form-control" asp-for="Date">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Odometer Total Reading</label>
        <input type="number" class="form-control" asp-for="odometerTotal">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Filled Volume</label>
        <input type="number" class="form-control" asp-for="filledVolume">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Fuel Price</label>
        <input type="number" class="form-control" asp-for="fuelPrice">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Filled? (Enter Yes or NO)</label>
        <input type="text" class="form-control" asp-for="filled">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/FuelData/Index.cshtml
@model List<Fuel_Tracking_application.Models.Domain.Fuel>


@{
}

<h1>Fuel Data</h1>

<table class="table"> 
    <thead>
    <tr>
        <th>Id</th>
        <th>Reporting Employee Name</th>
        <th>Date of Log</th>
        <th>Odometer Total Reading</th>
        <th>Filled Volume</th>
        <th>Fuel Price</th>
        <th>Filled?</th>
        <th>Edit</th>

    </tr>
    </thead>

<tbody>
    @foreach (var fuel in Model)
    {
        <tr>
            <td>@fuel.dataId</td>
            <td>@fuel.reportingEmployee</td>
            <td>@fuel.Date.ToString("dd-MM-yyyy")</td>
            <td>@fuel.odometerTotal</td>
            <td>@fuel.filledVolume</td>
            <td>@fuel.fuelPrice</td>
            <td>@fuel.filled</td>
            <td><a href="FuelData/View/@fuel.dataId">Edit</a></td>
        </tr>
    }       
</tbody>
</table>

<a href="@Url.Action("ExportToExcel", "Home")">Export to Excel</a>

Views/FuelData/View.cshtml
@model Fuel_Tracking_application.Models.UpdateFuelDataModel
@{
}


<h1>Edit Fuel Data</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Instance ID</label>
        <input type="text" class="form-control" asp-for="dataId" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Reporting Employee Name</label>
        <input type="text" class="form-control" asp-for="reportingEmployee">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date of Log</label>
        <input type="date" class="form-control" asp-for="Date">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Odometer Total Reading</label>
        <input type="number" class="form-control" asp-for="odometerTotal">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Filled Volume</label>
        <input type="number" class="form-control" asp-for="filledVolume">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Fuel Price</label>
        <input type="number" class="form-control" asp-for="fuelPrice">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Filled? (Enter Yes or NO)</label>
        <input type="text" class="form-control" asp-for="filled">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn-danger" asp-action="Delete" asp-controller="FuelData">Delete</button>



</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fuel_Tracking_application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fuel_Tracking_application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fuel Tracking Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapsed-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FuelData" asp-action="Add">Add Fuel Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FuelData" asp-action="Index">View Fuel Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Thabiso Rantsho - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>